version: 1.0

description: A basic workflow with error on action evaluation in one of the tasks.

input:
  - who

vars:
  - func: "core.echo"
  - msg1: "Veni, vidi, vici."
  - msg2: "Resistance is futile!"
  - msg3: "All your base are belong to us!"

tasks:
  task1:
    action: core.echo message=<% ctx().msg1 %>
    next:
      - when: <% succeeded() %>
        do: task2
  task2:
    action: <% ctx().func.value %>
    input:
        message: <% ctx().msg2 %>
    next:
      - when: <% succeeded() %>
        do: task3
  task3:
    action: core.echo
    input:
        message: <% ctx().who %>, <% ctx().msg3 %>
